services:
  postgres:
    container_name: postgres-bsn
    image: postgres:15.15-bookworm
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_social_network
    volumes:
      - bsn-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bsn-network
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - bsn-network
    restart: unless-stopped
networks:
  bsn-network:
    driver: bridge
volumes:
  bsn-data:
    driver: local

