services:
  mysql:
    container_name: mysql-bns
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bns
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - bns-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - bns-network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bns
    image: maildev/maildev
    ports:
      - "1081:1080"
      - "1026:1025"
    networks:
      - bns-network
    restart: unless-stopped

networks:
  bns-network:
    driver: bridge

volumes:
  bns-data:
    driver: local